- .gitignore
- components/org.wso2.carbon.identity.local.auth.emailotp/pom.xml
- components/org.wso2.carbon.identity.local.auth.emailotp/src/main/java/org/wso2/carbon/identity/local/auth/emailotp/EmailOTPAuthenticator.java
- components/org.wso2.carbon.identity.local.auth.emailotp/src/main/java/org/wso2/carbon/identity/local/auth/emailotp/connector/EmailOTPAuthenticatorConfigImpl.java
- components/org.wso2.carbon.identity.local.auth.emailotp/src/main/java/org/wso2/carbon/identity/local/auth/emailotp/constant/AuthenticatorConstants.java
- components/org.wso2.carbon.identity.local.auth.emailotp/src/main/java/org/wso2/carbon/identity/local/auth/emailotp/exception/EmailOtpAuthenticatorException.java
- components/org.wso2.carbon.identity.local.auth.emailotp/src/main/java/org/wso2/carbon/identity/local/auth/emailotp/exception/EmailOtpAuthenticatorServerException.java
- components/org.wso2.carbon.identity.local.auth.emailotp/src/main/java/org/wso2/carbon/identity/local/auth/emailotp/internal/AuthenticatorDataHolder.java
- components/org.wso2.carbon.identity.local.auth.emailotp/src/main/java/org/wso2/carbon/identity/local/auth/emailotp/internal/AuthenticatorServiceComponent.java
- components/org.wso2.carbon.identity.local.auth.emailotp/src/main/java/org/wso2/carbon/identity/local/auth/emailotp/util/AuthenticatorUtils.java
- components/org.wso2.carbon.identity.local.auth.emailotp/src/test/java/com/wso2/identity/asgardeo/auth/emailotp/EmailOTPAuthenticatorTest.java
- features/org.wso2.carbon.identity.local.auth.emailotp.server.feature/pom.xml
- pom.xml
Onboard the new email otp authenticator implemented as a local authenticator.
Implemented https://github.com/wso2/product-is/issues/16306
> Add initial implementation of the authenticator

- components/org.wso2.carbon.identity.local.auth.emailotp/pom.xml
- components/org.wso2.carbon.identity.local.auth.emailotp/src/main/java/org/wso2/carbon/identity/local/auth/emailotp/EmailOTPAuthenticator.java
- components/org.wso2.carbon.identity.local.auth.emailotp/src/main/java/org/wso2/carbon/identity/local/auth/emailotp/constant/AuthenticatorConstants.java
- components/org.wso2.carbon.identity.local.auth.emailotp/src/test/java/org/wso2/carbon/identity/local/auth/emailotp/EmailOTPAuthenticatorTest.java
- pom.xml
* Add initial diagnostic logs to the email otp
* Fix the failing test cases when bumping the version of the framework
Diagnostic logs will be covered the green-colored actions/validations of the authentication process. 
1. Authentication Request Validation
Within each authenticator, the `initiateAuthenticationRequest` method houses the logic for this step. This triggers two diagnostic logs. The first log indicates when authentication validation starts, and the second log shows the result of the validation – whether it's a Success or marked Invalid.
2. Validate Authentication Response
The `processAuthenticationResponse` method handles authentication response validation. Once users are sent to the authentication page and complete the process, the authenticator receives an authentication …
> Add diagnostic logs

- components/org.wso2.carbon.identity.local.auth.emailotp/src/main/java/org/wso2/carbon/identity/local/auth/emailotp/EmailOTPAuthenticator.java
> Improve diagnostic logs

- components/org.wso2.carbon.identity.local.auth.emailotp/src/main/java/org/wso2/carbon/identity/local/auth/emailotp/EmailOTPAuthenticator.java
- components/org.wso2.carbon.identity.local.auth.emailotp/src/main/java/org/wso2/carbon/identity/local/auth/emailotp/constant/AuthenticatorConstants.java
- pom.xml
> This PR introduces diagnostic logs at the point where email sending task is triggered.
- Issue https://github.com/wso2-enterprise/wso2-iam-internal/issues/769
> Add diagnostic log for trigger email

- components/org.wso2.carbon.identity.local.auth.emailotp/src/main/java/org/wso2/carbon/identity/local/auth/emailotp/EmailOTPAuthenticator.java
- components/org.wso2.carbon.identity.local.auth.emailotp/src/main/java/org/wso2/carbon/identity/local/auth/emailotp/constant/AuthenticatorConstants.java
- components/org.wso2.carbon.identity.local.auth.emailotp/src/test/java/org/wso2/carbon/identity/local/auth/emailotp/EmailOTPAuthenticatorTest.java
- pom.xml
Add API_Based Authentication Related configurations to the email otp
> Add API_Based Authentication Related configurations to the email otp

- components/org.wso2.carbon.identity.local.auth.emailotp/src/main/java/org/wso2/carbon/identity/local/auth/emailotp/EmailOTPAuthenticator.java
- components/org.wso2.carbon.identity.local.auth.emailotp/src/main/java/org/wso2/carbon/identity/local/auth/emailotp/constant/AuthenticatorConstants.java
- components/org.wso2.carbon.identity.local.auth.emailotp/src/test/java/org/wso2/carbon/identity/local/auth/emailotp/EmailOTPAuthenticatorTest.java
- pom.xml
Modify the authenticator based on the modifications done for the service
> Modify the authenticator based on the modifications done for the service

- components/org.wso2.carbon.identity.local.auth.emailotp/src/main/java/org/wso2/carbon/identity/local/auth/emailotp/EmailOTPAuthenticator.java
- components/org.wso2.carbon.identity.local.auth.emailotp/src/test/java/org/wso2/carbon/identity/local/auth/emailotp/EmailOTPAuthenticatorTest.java
Modify the authenticator to match with the service
> Modify the authenticator to match with the service

- components/org.wso2.carbon.identity.local.auth.emailotp/src/main/java/org/wso2/carbon/identity/local/auth/emailotp/EmailOTPAuthenticator.java
- pom.xml
Modified a few private methods with context details to be used in the handleAuthErrorScenario
> Modify error handling in email otp

- components/org.wso2.carbon.identity.local.auth.emailotp/src/main/java/org/wso2/carbon/identity/local/auth/emailotp/EmailOTPAuthenticator.java
This PR addresses the review comments for PR https://github.com/wso2-enterprise/asgardeo-extensions/pull/142
> Address review comments

- components/org.wso2.carbon.identity.local.auth.emailotp/src/main/java/org/wso2/carbon/identity/local/auth/emailotp/EmailOTPAuthenticator.java
Set message to AuthenticatorData
> Set message to AuthenticatorData

- components/org.wso2.carbon.identity.local.auth.emailotp/src/main/java/org/wso2/carbon/identity/local/auth/emailotp/EmailOTPAuthenticator.java
> Avoid possible null pointer

- components/org.wso2.carbon.identity.local.auth.emailotp/src/main/java/org/wso2/carbon/identity/local/auth/emailotp/EmailOTPAuthenticator.java
- components/org.wso2.carbon.identity.local.auth.emailotp/src/main/java/org/wso2/carbon/identity/local/auth/emailotp/constant/AuthenticatorConstants.java
- pom.xml
> Add displayName

- components/org.wso2.carbon.identity.local.auth.emailotp/src/main/java/org/wso2/carbon/identity/local/auth/emailotp/constant/AuthenticatorConstants.java
$subject
Related issue: 
- https://github.com/wso2/product-is/issues/17840
> Change typo error in Email OTP error message

- components/org.wso2.carbon.identity.local.auth.emailotp/src/main/java/org/wso2/carbon/identity/local/auth/emailotp/EmailOTPAuthenticator.java
> $subject
- https://github.com/wso2/product-is/issues/17962
> Added multiOptionURI parameter to the redirect url in the identifier-first authenticator

- components/org.wso2.carbon.identity.local.auth.emailotp/src/main/java/org/wso2/carbon/identity/local/auth/emailotp/EmailOTPAuthenticator.java
Fix https://github.com/wso2/product-is/issues/17865
> Fix https://github.com/wso2/product-is/issues/17865

- components/org.wso2.carbon.identity.local.auth.emailotp/src/main/java/org/wso2/carbon/identity/local/auth/emailotp/EmailOTPAuthenticator.java
> Set i18n key as metadata

- components/org.wso2.carbon.identity.local.auth.emailotp/src/main/java/org/wso2/carbon/identity/local/auth/emailotp/EmailOTPAuthenticator.java
- pom.xml
> Add app tenant domain to event properties

- components/org.wso2.carbon.identity.local.auth.emailotp/src/main/java/org/wso2/carbon/identity/local/auth/emailotp/EmailOTPAuthenticator.java
> Fix branding is not applied for Email OTP email. 

- components/org.wso2.carbon.identity.local.auth.emailotp/src/main/java/org/wso2/carbon/identity/local/auth/emailotp/EmailOTPAuthenticator.java
- components/org.wso2.carbon.identity.local.auth.emailotp/src/main/java/org/wso2/carbon/identity/local/auth/emailotp/constant/AuthenticatorConstants.java
> Fix issues with locked account flow

- components/org.wso2.carbon.identity.local.auth.emailotp/src/main/java/org/wso2/carbon/identity/local/auth/emailotp/EmailOTPExecutor.java
- components/org.wso2.carbon.identity.local.auth.emailotp/src/main/java/org/wso2/carbon/identity/local/auth/emailotp/constant/ExecutorConstants.java
$subject
https://github.com/wso2/product-is/issues/23356
> Set email verified claim to true

- components/org.wso2.carbon.identity.local.auth.emailotp/src/main/java/org/wso2/carbon/identity/local/auth/emailotp/CommonUtils.java
- components/org.wso2.carbon.identity.local.auth.emailotp/src/main/java/org/wso2/carbon/identity/local/auth/emailotp/EmailOTPExecutor.java
- components/org.wso2.carbon.identity.local.auth.emailotp/src/main/java/org/wso2/carbon/identity/local/auth/emailotp/constant/ExecutorConstants.java
$subject
https://github.com/wso2/product-is/issues/23356
> Handle max retry attempts and return OTP length

- components/org.wso2.carbon.identity.local.auth.emailotp/src/main/java/org/wso2/carbon/identity/local/auth/emailotp/CommonUtils.java
- components/org.wso2.carbon.identity.local.auth.emailotp/src/main/java/org/wso2/carbon/identity/local/auth/emailotp/EmailOTPExecutor.java
- components/org.wso2.carbon.identity.local.auth.emailotp/src/test/java/org/wso2/carbon/identity/local/auth/emailotp/EmailOTPExecutorTest.java
$subject
https://github.com/wso2/product-is/issues/23356
> Add unit tests to EmailOTPExecutor

- components/org.wso2.carbon.identity.local.auth.emailotp/src/main/java/org/wso2/carbon/identity/local/auth/emailotp/EmailOTPAuthenticator.java
- components/org.wso2.carbon.identity.local.auth.emailotp/src/main/java/org/wso2/carbon/identity/local/auth/emailotp/constant/AuthenticatorConstants.java
- components/org.wso2.carbon.identity.local.auth.emailotp/src/test/java/org/wso2/carbon/identity/local/auth/emailotp/EmailOTPAuthenticatorTest.java
Reverts wso2-extensions/identity-local-auth-emailotp#41
> Revert "Unify OTP Parameter Handling in Email OTP Authenticator"

- components/org.wso2.carbon.identity.local.auth.emailotp/src/main/java/org/wso2/carbon/identity/local/auth/emailotp/EmailOTPAuthenticator.java
- components/org.wso2.carbon.identity.local.auth.emailotp/src/main/java/org/wso2/carbon/identity/local/auth/emailotp/constant/AuthenticatorConstants.java
- components/org.wso2.carbon.identity.local.auth.emailotp/src/test/java/org/wso2/carbon/identity/local/auth/emailotp/EmailOTPAuthenticatorTest.java
Reverts wso2-extensions/identity-local-auth-emailotp#47
> Revert "Fix OTP sending failure due to OTPCode set from SMS OTP Authenticator"

- components/org.wso2.carbon.identity.local.auth.emailotp/src/main/java/org/wso2/carbon/identity/local/auth/emailotp/EmailOTPExecutor.java
- components/org.wso2.carbon.identity.local.auth.emailotp/src/test/java/org/wso2/carbon/identity/local/auth/emailotp/EmailOTPExecutorTest.java
> $subject
https://github.com/wso2/product-is/issues/23684
> Improve retry and expired scenario handling in email OTP executor

- components/org.wso2.carbon.identity.local.auth.emailotp/src/main/java/org/wso2/carbon/identity/local/auth/emailotp/EmailOTPAuthenticator.java
- pom.xml
**Related Issues**
- https://github.com/wso2/product-is/issues/24183
This pull request updates the Email OTP authenticator to use a more generic OTP captcha connector and brings the identity governance dependency up to date. The changes improve maintainability and compatibility with newer platform features.
> Fix emailotp recaptcha
